
service: mehrnebel # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 256
  stage: dev
  region: eu-west-1
  profile: default
  environment:
    USER_POOL_ID: ${cf:login-cognito-userpool.cognitoUserPool}
    USER_POOL_CLIENT_ID: ${cf:login-cognito-userpool.cognitoUserPoolClient}
    USER_POOL_LOGIN_URL: ${cf:login-cognito-userpool.userPoolDomain}
    ASSETS_DOMAIN_NAME: ${cf:mehrnebel-assets.distributionName}


plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline


custom:
  webpack: ./webpack.server.config.js
  webpackIncludeModules: true
  dynamodb:
    start:
      migrate: true
      port: 8000
  serverless-offline:
    port: 2999
    babelOptions:
      presets: ["es2015", "stage-2"]

functions:
  index:
    handler: lib/server/handlers/indexHandler.login
    events:
      - http:
          method: GET
          path: /
          integration: lambda
          request: ${file(./serverless.templates.yml):request-html}
          response: ${file(./serverless.templates.yml):response-html}
      - http:
          method: GET
          path: /buzzer
          integration: lambda
          request: ${file(./serverless.templates.yml):request-html}
          response: ${file(./serverless.templates.yml):response-html}
  createFog:
    handler: lib/server/handlers/pushHandler.createFog
    events:
      - http:
          method: GET
          path: /create-fog
          integration: lambda
          authorizer:
            arn: ${cf:login-cognito-userpool.cognitoArnPool}
            claims:
              - email
              - name
              - cognito:username

resources:
   Resources:
     userStatsTable:
       Type: AWS::DynamoDB::Table
       Properties:
         TableName: usersStatsTable
         AttributeDefinitions:
           - AttributeName: username
             AttributeType: S
         KeySchema:
           - AttributeName: username
             KeyType: HASH
         ProvisionedThroughput:
           ReadCapacityUnits: 1
           WriteCapacityUnits: 1
   Outputs:
      UsersStatsTable:
        Description: The Id of the restapi
        Value:
          'Ref': userStatsTable

      ApiGatewayRestApiId:
        Description: The Id of the restapi
        Value:
          'Ref': ApiGatewayRestApi
