
service: mehrnebel # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 256
  stage: dev
  region: eu-central-1
  profile: default
  environment:
    USER_POOL_ID: ${cf:login-cognito-userpool.cognitoUserPool}
    USER_POOL_CLIENT_ID: ${cf:login-cognito-userpool.cognitoUserPoolClient}
    USER_POOL_LOGIN_URL: ${cf:login-cognito-userpool.userPoolDomain}
    ASSETS_DOMAIN_NAME: ${cf:mehrnebel-assets.distributionName}
    IOT_ENDPOINT: ${cf:thing-smoke-machine.thingEndpoint}
    DYNAMO_REGION: ${opt:region}
    DYNAMO_TABLE_NAME: usersStatsTable


plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline


custom:
  webpack: ./webpack.server.config.js
  webpackIncludeModules: true
  dynamodb:
    start:
      migrate: true
      port: 8000
  serverless-offline:
    port: 2999
    babelOptions:
      presets: ["es2015", "stage-2"]

functions:
  index:
    handler: lib/server/handlers/indexHandler.login
    events:
      - http:
          method: GET
          path: /
          integration: lambda
          request: ${file(./serverless.templates.yml):request-html}
          response: ${file(./serverless.templates.yml):response-html}
      - http:
          method: GET
          path: /buzzer
          integration: lambda
          request: ${file(./serverless.templates.yml):request-html}
          response: ${file(./serverless.templates.yml):response-html}
  createFog:
    handler: lib/server/handlers/pushHandler.createFog
    events:
      - http:
          method: PUT
          path: /api/create-fog
          integration: lambda
          authorizer:
            arn: ${cf:login-cognito-userpool.cognitoArnPool}
            claims:
              - email
              - name
              - cognito:username
  getUser:
    handler: lib/server/handlers/pushHandler.getUser
    events:
      - http:
          method: GET
          path: /api/user
          integration: lambda
          authorizer:
            arn: ${cf:login-cognito-userpool.cognitoArnPool}
            claims:
              - email
              - name
              - cognito:username

resources:
   Resources:
     userStatsTable:
       Type: AWS::DynamoDB::Table
       Properties:
         TableName: usersStatsTable
         AttributeDefinitions:
           - AttributeName: username
             AttributeType: S
         KeySchema:
           - AttributeName: username
             KeyType: HASH
         ProvisionedThroughput:
           ReadCapacityUnits: 1
           WriteCapacityUnits: 1
     DynamoDBIamPolicy:
       Type: AWS::IAM::Policy
       DependsOn: userStatsTable
       Properties:
         PolicyName: lambda-dynamodb
         PolicyDocument:
           Version: '2012-10-17'
           Statement:
             - Effect: Allow
               Action:
                 - dynamodb:GetItem
                 - dynamodb:PutItem
                 - dynamodb:UpdateItem
               Resource: arn:aws:dynamodb:*:*:table/usersStatsTable
         Roles:
           - Ref: IamRoleLambdaExecution
     IotIamPolicy:
       Type: AWS::IAM::Policy
       Properties:
         PolicyName: lambda-iot
         PolicyDocument:
           Version: '2012-10-17'
           Statement:
             - Effect: Allow
               Action:
                 - iot:Publish
               Resource: arn:aws:iot:*:*:topic/mehrnebel
         Roles:
           - Ref: IamRoleLambdaExecution
   Outputs:
      UsersStatsTableName:
        Description: The Id of the restapi
        Value:
          'Ref': userStatsTable
      ApiGatewayRestApiId:
        Description: The Id of the restapi
        Value:
          'Ref': ApiGatewayRestApi
