region: eu-west-1

stacks:
  mehrnebel-assets:
    template-url: templates/assets.yaml
    timeout: 1200
    parameters:
      bucketName: 'mehrnebel-assets'
      # random identifier
      originId: 's3-mehrnebel-assets'
      originPath: '/assets'
