region: eu-central-1

stacks:
  mehrnebel-assets:
    template-url: templates/assets.yaml
    timeout: 1200
    parameters:
      assetsBucketName: 'mehrnebel-assets'
      pageBucketName: 'mehrnebel.cornetto.cloud'
      # random identifier
      originId: 's3-mehrnebel-assets'
      originPath: '/assets'
