AWSTemplateFormatVersion: '2010-09-09'
Description: Assets (S3 and Cloudfront) for mehrnebel
Parameters:
  pageBucketName:
    Description: page bucket name
    Type: String

  originId:
    Description: an origin id for cloudfront
    Type: String
  originPath:
    Description: an origin path for cloudfront (folder in s3)
    Type: String



# -----------------------------------------------------------------------------------------
Resources:
# -----------------------------------------------------------------------------------------
  # Html Page
  S3PageBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref pageBucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: AllowPublicAccessToBucketPolicy
        Version: '2012-10-17'
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: 's3:GetObject'
          Resource: !Sub arn:aws:s3:::${S3PageBucket}/*
      Bucket: !Ref S3PageBucket




# -----------------------------------------------------------------------------------------
# OUTPUTS
# -----------------------------------------------------------------------------------------
Outputs:
  pageBucketName:
    Value: !Ref S3PageBucket
    Description: assets s3 bucket resource name

