AWSTemplateFormatVersion: '2010-09-09'
Description: Assets (S3 and Cloudfront) for mehrnebel
Parameters:
  assetsBucketName:
    Description: Assets bucket name
    Type: String
  pageBucketName:
    Description: page bucket name
    Type: String

  originId:
    Description: an origin id for cloudfront
    Type: String
  originPath:
    Description: an origin path for cloudfront (folder in s3)
    Type: String



# -----------------------------------------------------------------------------------------
Resources:
# -----------------------------------------------------------------------------------------

  S3AssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref assetsBucketName


  CloudfrontDistribution:
    Type : AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !GetAtt S3AssetsBucket.DomainName
            Id: !Ref originId
            OriginPath: !Ref originPath
            S3OriginConfig: {}
        PriceClass: PriceClass_100
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
          TargetOriginId: !Ref originId
          ViewerProtocolPolicy: 'https-only'

  S3PageBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref pageBucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: AllowPublicAccessToBucketPolicy
        Version: '2012-10-17'
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: 's3:GetObject'
          Resource: !Sub arn:aws:s3:::${S3PageBucket}/*
      Bucket: !Ref S3Bucket




# -----------------------------------------------------------------------------------------
# OUTPUTS
# -----------------------------------------------------------------------------------------
Outputs:
  bucketName:
    Value: '|Ref|S3AssetsBucket'
    Description: assets s3 bucket resource name
  distributionName:
    Value: !GetAtt CloudfrontDistribution.DomainName
    Description: domain name of cloudfront distribution

