AWSTemplateFormatVersion: '2010-09-09'
Description: DNS/Route53 config for mehrnebel.cornetto.cloud
Parameters:
  dnsPrefix:
    Description: DNS Domain prefix, e.g. 'mehrnebel'
    Type: String

  dnsBaseName:
    Description: DNS Domain , f.e. 'cornetto.cloud.'
    ConstraintDescription: "Value must be a dns name and end with a dot"
    AllowedPattern: ".*"
    Type: String

  apiDomain:
    Description: Url for rest api
    Type: String

  homepageS3Bucket:
    Description: s3 bucket for the homepage
    Type: String

  certificateArn:
    Description: Certifcate ARN
    Type: String


# -----------------------------------------------------------------------------------------
Resources:
  # -----------------------------------------------------------------------------------------

  # -----------------------------------------------------------------------------------------
  # DNS Route53
  # -----------------------------------------------------------------------------------------
  CloudfrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        HttpVersion: http2
        Enabled: true
        Aliases:
        - !Sub ${dnsPrefix}.${dnsBaseName}
        ViewerCertificate:
          AcmCertificateArn: !Ref certificateArn
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
        # Homepage
          AllowedMethods:
          - GET
          - HEAD
          DefaultTTL: 60
          MaxTTL: 60
          MinTTL: 60
          TargetOriginId: mehrnebel-homepage
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false


        CacheBehaviors:
        # Assets
        - AllowedMethods:
          - GET
          - HEAD
          DefaultTTL: 31536000
          MaxTTL: 31536000
          MinTTL: 31536000
          PathPattern: /assets/*
          TargetOriginId: mehrnebel-homepage
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
        # REST API
        - AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          PathPattern: /api/*
          TargetOriginId: mehrnebel-api
          ViewerProtocolPolicy: redirect-to-https
          SmoothStreaming: 'false'
          ForwardedValues:
            Headers:
              - 'authorization'
            QueryString: true
        CustomErrorResponses:
        - ErrorCode: '404'
          ErrorCachingMinTTL: 0
          ResponsePagePath: /
          ResponseCode: 200
        Origins:
          - CustomOriginConfig:
#              OriginProtocolPolicy: https-only
#              OriginSSLProtocols:
#              - TLSv1.2
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: 'http-only'

            DomainName: !Sub ${homepageS3Bucket}.s3-website.${AWS::Region}.amazonaws.com
            Id: mehrnebel-homepage

          - CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
              - TLSv1.2
            DomainName: !Ref apiDomain
            Id: mehrnebel-api

  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub ${dnsBaseName}.
      Comment: Route alias
      Name: !Sub ${dnsPrefix}.${dnsBaseName}.
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudfrontDistribution.DomainName
        HostedZoneId: 'Z2FDTNDATAQYW2' #Zone Id for Cloudfront, see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html

# -----------------------------------------------------------------------------------------
# OUTPUTS
# -----------------------------------------------------------------------------------------
#Outputs:
  #  dnsRecord:
  #    Value: '|Ref|dnsRecord'
  #    Description: DB dns name
#  certificate:
#    Value: '|Ref|Certificate'
#    Description: certificate ARN

