AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito User pool template
Parameters:
  poolName:
    Description: Cognito User Pool Name
    Type: String
  domainName:
    Description: Cognito Url Domain Name
    Type: String
  customResourceServiceToken:
    Description: Service token for custom resource
    Type: String


# -----------------------------------------------------------------------------------------
Resources:
# -----------------------------------------------------------------------------------------

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${poolName}-pool
      AliasAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: false
          RequireSymbols: false

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${poolName}-client
      GenerateSecret: false
      UserPoolId: !Ref CognitoUserPool

  UserPoolDomain:
    Type: Custom::CognitoUserPoolDomain
    Properties:
      ServiceToken: !Ref customResourceServiceToken
      Service: CognitoIdentityServiceProvider
      PhysicalResourceId: !Ref domainName
      Parameters:
        UserPoolId: !Ref CognitoUserPool
        Domain: !Ref domainName
      Create:
        Action: createUserPoolDomain
      Update:
        # Updates are not fully supported. This will delete the previous domain name.
        # You will have to create the new domain name manually through the API or console.
        Action: deleteUserPoolDomain
        IgnoreErrors: true
      Delete:
        Action: deleteUserPoolDomain
        IgnoreErrors: true

  UserPoolClientSettings:
    Type: Custom::CognitoUserPoolClientSettings
    Properties:
      ServiceToken: !Ref customResourceServiceToken
      Service: CognitoIdentityServiceProvider
      Create:
        Action: updateUserPoolClient
        Parameters:
          UserPoolId: !Ref CognitoUserPool
          ClientId: !Ref UserPoolClient
          AllowedOAuthFlows: [code, implicit]
          AllowedOAuthScopes: [openid]
          SupportedIdentityProviders: [COGNITO]
          AllowedOAuthFlowsUserPoolClient: true
          CallbackURLs:
            - 'https://mehrnebel.cornetto.cloud'
          LogoutUrls:
            - 'https://dutrinkst.cornetto.cloud'


# -----------------------------------------------------------------------------------------
# OUTPUTS
# -----------------------------------------------------------------------------------------
Outputs:
  cognitoUserPool:
    Value: '|Ref|CognitoUserPool'
    Description: Cognito User Pool Id
  cognitoArnPool:
    Value: !GetAtt CognitoUserPool.Arn
    Description: Cognito User Pool ARN
  cognitoUserPoolClient:
    Value: !Ref UserPoolClient
    Description: Cognito User Pool ARN
  userPoolDomain:
    Value: !Sub ${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com
    Description: User Pool Domain


