AWSTemplateFormatVersion: '2010-09-09'
Description: AWS IOT Things
Parameters:
  topicName:
    Description: Name of the topic
    Type: String

# -----------------------------------------------------------------------------------------
Resources:
# -----------------------------------------------------------------------------------------
  IotBrowserRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 43200
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: IOTConnect
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - iot:Subscribe
            - iot:Publish
            - iot:Receive
#            Resource: !Sub arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topic/${topicName}
            Resource:
              - !Sub arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topic/${topicName}
              - !Sub arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topicfilter/${topicName}
            Effect: Allow
          - Action:
            - iot:Connect
            Resource: "*"
            Effect: Allow




# -----------------------------------------------------------------------------------------
# OUTPUTS
# -----------------------------------------------------------------------------------------
Outputs:
  roleArn:
    Value: !GetAtt IotBrowserRole.Arn
    Description: Name of a thing

